server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8081"
              - "http://127.0.0.1:8082"
              - "http://localhost:8082"
              - "http://127.0.0.1:8082"
              - "http://heima.liliudong.com"
            allowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/*
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/*

